### PR TITLE
Zhiping version

### PR DESCRIPTION
**Pull request by smartlinux**
When there are several (>1)  transport zone, the code does not work.
This modification is to fix this problem.

### CODE REVIEW

**Comment by yfauser** [comment]
@smartlinux Thanks for your Pull request! There's already a similar fix in the devel branch (https://github.com/vmware/pynsxv/commit/205d9a7523dd6f95b4ac390eb3d612223fa2bdd6), therefore it's going to be hard for me to merge your PR.
But this reminds me that I really need to release a new version soon, as Devel is 30+ commits ahead, and we did not have a lot of time to work on closing the open feature issue recently.
Would you also be able and willing to work on features?

**Comment by smartlinux** [comment]
@yfauser<https://github.com/yfauser>

Thank you for your reply.
I’m willing to work on it. But unfortunately, I’m just starting to use pynsxv and just starting to study python.
I’m afraid that I can’t do it effectively now.


Anyway, thank you very much.

**Comment by yfauser** [comment]
Sure, let me know if I can help you getting up to speed!

**Comment by smartlinux** [comment]
Has been fixed on other branch.

**Pull request closed without merging**
